name: test

services:
  # logger:
  #   image: fluentd:latest
  #   ports:
  #     - 24224:24224
  #     - 24224:24224/udp
  #   volumes:
  #     - logger:/fluentd/log

  bit-workspace:
    image: iham/bit-vscode-workspace:latest
    restart: unless-stopped
    volumes:
      - bit-workspace:/bit-workspace
    ports: 
      - 8000:8080
    # logging:
    #   driver: fluentd
    #   options:
    #     fluentd-address: "logger:24224"
    #     tag: "my-db"

  scope-1:
    image: iham/bit-server:latest
    restart: unless-stopped
    environment:
      - SCOPE_NAME=scope-1
    volumes:
      - scope-1:/bit-scope
    ports: 
      - 8100:3000

  scope-2:
    image: iham/bit-server:latest
    restart: unless-stopped
    environment:
      - SCOPE_NAME=scope-2
    volumes:
      - scope-2:/bit-scope
    ports: 
      - 8200:3000

# Lets reflect the scopes to the local filesystem for later use and inspection
volumes:
  # logger:
  #   driver: local
  #   driver_opts:
  #     type: none
  #     device: "../logger"
  #     o: bind
  bit-workspace:
    driver: local
    driver_opts:
      type: none
      device: "../bit-workspace"
      o: bind
  scope-1:
    driver: local
    driver_opts:
      type: none
      device: "../scope-1"
      o: bind
  scope-2:
    driver: local
    driver_opts:
      type: none
      device: "../scope-2"
      o: bind
