name: test

services:
  bit-workspace:
    image: iham/bit-vscode-workspace:latest
    restart: unless-stopped
    volumes:
      - ../bit-workspace:/bit-workspace
    ports: 
      - 8000:8080

  scope-1:
    image: iham/bit-server:latest
    restart: unless-stopped
    environment:
      - SCOPE_NAME=scope-1
    volumes:
      - scope-1:/bit-scope
    ports: 
      - 8100:3000

  scope-2:
    image: iham/bit-server:latest
    restart: unless-stopped
    environment:
      - SCOPE_NAME=scope-2
    volumes:
      - scope-2:/bit-scope
    ports: 
      - 8200:3000

volumes:
  scope-1:
    driver: local
    driver_opts:
      type: none
      device: "../scope-1"
      o: bind
  scope-2:
    driver: local
    driver_opts:
      type: none
      device: "../scope-2"
      o: bind
