name: test

services:
  # logger:
  #   image: fluentd:latest
  #   ports:
  #     - 24224:24224
  #     - 24224:24224/udp
  #   volumes:
  #     - logger:/fluentd/log

  workspace:
    image: iham/bit-vscode-workspace:latest
    restart: unless-stopped
    volumes:
      - bit-workspace:/bit-workspace
    ports: 
      - 8000:8080
    # logging:
    #   driver: fluentd
    #   options:
    #     fluentd-address: "logger:24224"
    #     tag: "my-db"

  mfe-1:
    image: iham/bit-server:latest
    restart: unless-stopped
    environment:
    volumes:
      - mfe-1:/data
    ports: 
      - 8100:3000

  mfe-2:
    image: iham/bit-server:latest
    restart: unless-stopped
    environment:
    volumes:
      - mfe-2:/data
    ports: 
      - 8200:3000

# Lets reflect the scopes to the local filesystem for later use and inspection
volumes:
  # logger:
  #   driver: local
  #   driver_opts:
  #     type: none
  #     device: "../logger"
  #     o: bind
  workspace:
    driver: local
    driver_opts:
      type: none
      device: "../workspace"
      o: bind
  mfe-1:
    driver: local
    driver_opts:
      type: none
      device: "../mfe-1"
      o: bind
  mfe-2:
    driver: local
    driver_opts:
      type: none
      device: "../mfe-2"
      o: bind
